### ISSUE TITLE
lock_timeout not being used?

### ISSUE THREAD

**Issue by bsimpson** [wallace/resque-lonely_job#1]
Hey Jonathan,

I was looking at the source for this gem to determine when a lock would be released on its own. It seems that you have declared a lock_timeout on line 8 of https://github.com/wallace/resque-lonely_job/blob/master/lib/resque-lonely_job.rb

This value is never referenced when the lock is checked however. Is lock_timeout something that Resque is using? I expected to see the time in this lock file compared to the current time when the lock file is checked.

Thanks in advance for any help in clearing up my confusion.

**Comment by wallace** [comment]
Hey Ben,

The lock_timeout is not being used but if you check out the [redis SETNX documentation](http://redis.io/commands/setnx), you'll see a section on handling deadlocks that is relevant and the reason I included the lock_timeout in the first place.

Does that help?

**Comment by miyagawa** [comment]
This bites me earlier today, i was hoping it was actually checking the timeout a la redis-mutex [using getset](https://github.com/kenn/redis-mutex/blob/master/lib/redis/mutex.rb#L45). 

Also, the value created with the `lock_timeout` seems to return Time object to me, which is stored as a string in redis, which is not that useful - i think you should use `Time.now.to_i` instead of calling `.utc`.

**Comment by miyagawa** [comment]
I implemented a getset lock pattern on my fork: https://github.com/miyagawa/resque-lonely_job/commit/8ab67f6aaff3fd7c725f30d146ea3ddc791bb852

Let me know if you're interested in merging this. Will make a pull request.

**Comment by wallace** [comment]
@miyagawa , I'd be happy to merge this.  Would you be able to include tests for this too?  That would be amazing and awesome.

@bsimpson , would you be interested in this as well?

**Comment by miyagawa** [comment]
Added the test with mock_redis and timecop in https://github.com/miyagawa/resque-lonely_job/commit/644201de121cd14a59978e32207fc6f873e47dd2 Will make a PR.

**Comment by bsimpson** [comment]
@wallace Yup. I was looking for something like this a few months back.

**Comment by wallace** [comment]
Awesome, it has been merged and version 0.0.4 has been released to ruby gems.  Thanks @miyagawa!
