### ISSUE TITLE
Use Lonely Job with Resque Retry

### ISSUE THREAD

**Issue by adambedford** [wallace/resque-lonely_job#10]
I'm looking into using Lonely Job in conjunction with Resque Retry and have a couple questions thoughts:

I'm using "Option 3" from the Readme (as outlined here: https://www.bignerdranch.com/blog/never-use-resque-for-serial-jobs/) to preserve job ordering. This works great on its own however the argument stored in the Resque queue is no longer the actual argument required to perform the job; instead its the mutex used to pop the correct argument off a separate list.

If the job fails, Resque Retry will store the mutex argument and schedule a retry. This results in the wrong job being performed: the next job on the list will be performed, not the one that should be retried. In fact, the one to be retried doesn't actually get stored anywhere.

Has anyone run into a similar issue before?

**Comment by wallace** [comment]
I haven't used resque retry in conjunction with lonely job. Did you find a resolution to this issue?
