### ISSUE TITLE
Killing Lonely Job Returns to Queue

### ISSUE THREAD

**Issue by IbottaBaier** [wallace/resque-lonely_job#11]
When I `kill -9 <pid>` a Resque job I expect it to go to the failed jobs queue, but for some reason when I kill the lonely jobs they are going back to the regular queue they came from.

Nothing fancy in my job setup:
```
require 'resque-lonely_job'

class TheBestWorkerEver
  extend Resque::Plugins::LonelyJob
...
end
```

Not sure what other details to provide... 

Gem file:
```
# resque
gem 'resque', '~> 1.23', require: 'resque/server'
gem 'resque-scheduler'
gem 'redis'
gem 'hiredis'
gem 'redis-namespace', '~> 1.2'
gem 'resque-pool', '~> 0.6'
gem 'resque-dynamic-queues', '0.8.0', require: 'resque-dynamic-queues-server'
gem 'resque-queue-priority', '0.6.0', require: 'resque-queue-priority-server'
gem 'resque-lock-timeout', git: 'https://github.com/Ibotta/resque-lock-timeout.git', branch: 'args-normalization', require: false
gem 'resque-workers-lock'
gem 'resque-lonely_job'
```

Gem lock:
```
    resque (1.27.4)
      mono_logger (~> 1.0)
      multi_json (~> 1.0)
      redis-namespace (~> 1.3)
      sinatra (>= 0.9.2)
      vegas (~> 0.1.2)
    resque-dynamic-queues (0.8.0)
      resque (~> 1.10)
    resque-lonely_job (1.1.3)
      resque (>= 1.2)
    resque-pool (0.6.0)
      rake
      resque (~> 1.22)
    resque-queue-priority (0.6.0)
      resque (~> 1.10)
    resque-scheduler (4.3.0)
      mono_logger (~> 1.0)
      redis (~> 3.3)
      resque (~> 1.26)
      rufus-scheduler (~> 3.2)
    resque-workers-lock (2.0.1)
      resque
    resque_mailer (2.3.1)
      actionmailer (>= 3.0)
```

**Comment by IbottaBaier** [comment]
Update: I ended up find the lonely jobs that I killed in the failed jobs queue... but they also returned to the regular queue for processing.

**Comment by pboling** [comment]
The supported fork of this project is [`resque-unique_at_runtime`](https://github.com/pboling/resque-unique_at_runtime).  I am the maintainer of both, and I will be releasing a new version of this gem with an upgrade path toward [`resque-unique_at_runtime`](https://github.com/pboling/resque-unique_at_runtime).

I expect the behavior you were seeing here has been fixed, as the new fork has been used to process billions of jobs at [Intricately](https://www.intricately.com/) without issue.

Ref: https://github.com/wallace/resque-lonely_job/pull/13
