### ISSUE TITLE
Lonely Jobs Wasting Workers

### ISSUE THREAD

**Issue by IbottaBaier** [wallace/resque-lonely_job#12]
Each of my machines have four workers fed by two different queues, one of which is being populated with Lonely Job workers. I ended up having almost all workers full of Lonely Jobs... even though only one is able to run at a time. The lonely jobs that refuse to do work while another is in progress just stay at "just now" for their start time. 

Is this the expected behavior?

Example: 
Machine A
Worker 1: Lonely Job A (30 minutes)
Worker 2: Lonely Job A (just now) -- doing nothing
Worker 3: Lonely Job A (just now) -- doing nothing
Worker 4: Lonely Job A (just now) -- doing nothing

**Comment by pboling** [comment]
I'm not sure what the question is here.

The supported fork of this project is [`resque-unique_at_runtime`](https://github.com/pboling/resque-unique_at_runtime).  I am the maintainer of both, and I will be releasing a new version of this gem with an upgrade path toward [`resque-unique_at_runtime`](https://github.com/pboling/resque-unique_at_runtime).

Ref: https://github.com/wallace/resque-lonely_job/pull/13
