### ISSUE TITLE
Allow running N jobs at the same time

### ISSUE THREAD

**Issue by leanhdaovn** [wallace/resque-lonely_job#14]
Scenario: many jobs access service A with limited bandwith. We should keep the number of parallel jobs low in order not to overflow the service. 

However, 1 is too low. We want to set the max number to parallel jobs to, says 3, to balance the efficiency and the service health.

**Comment by pboling** [comment]
@leanhdaovn Interesting idea.  The supported fork of this project is [`resque-unique_at_runtime`](https://github.com/pboling/resque-unique_at_runtime).  I am the maintainer of both, and I will be releasing a new version of this gem with an upgrade path toward [`resque-unique_at_runtime`](https://github.com/pboling/resque-unique_at_runtime).

Ref: https://github.com/wallace/resque-lonely_job/pull/13
