### ISSUE TITLE
Resque dependency not clear

### ISSUE THREAD

**Issue by ksnyder** [wallace/resque-lonely_job#2]
Hi -- We're excited to try out your gem but not clear on the Resque dependency.  

Your write up says it works with Resque >= 1.20.0

but the gemspec says

gem.add_dependency 'resque', '~> 1.20.0'

which means >= 1.20.0 && < 1.21.0

and since we're on Resque 1.21.0 we're getting

Bundler could not find compatible versions for gem "resque":
  In Gemfile:
    resque-lonely_job (>= 0) ruby depends on
      resque (~> 1.20.0) ruby

```
resque (1.21.0)
```

**Comment by wallace** [comment]
@ksnyder, sorry for the delay in getting back to you.  The discrepancy between documentation and gemspec has been resolved in a recent pull request, #4.
