### ISSUE TITLE
Update the docs and the comment to indicate jobs that fail to get the lock are enqueued at the tail of the queue

### ISSUE THREAD

**Issue by justinmills** [wallace/resque-lonely_job#7]
The Readme indicates in a couple places that queue starvation is possible because a job that doesn't get the lock is enqueued at the head of the queue. I think there was a previous version that attempted to do that, but at least since version v0.0.4 that hasn't been the case. Resque.enqueue puts the job at the _tail_ of the queue so it'll be the last job processed. We've been using this plugin for quite some time now, very happy that jobs that do not get the lock are enqueued at the end of the queue allowing jobs that can get the lock to make their way through the queue.

``` ruby
      # Unfortunately, there's not a Resque interface for lpush so we have to
      # role our own.  This is based on Resque.push but we don't need to
      # call Resque.watch_queue as the queue should already exist if we're
      # unable to get the lock.
      def reenqueue(*args)
        Resque.enqueue(self, *args)
      end
```

**Comment by wallace** [comment]
@justin-yesware , you're correct! I'll update the README to clarify that the starvation possibility is dependent upon the implementation of `reenqueue` and remove this extraneous comment.
