### ISSUE TITLE
Do not hog 100% cpu when requeueing

### ISSUE THREAD

**Issue by lwoodson** [wallace/resque-lonely_job#8]
Steps to reproduce:
1.  Start 2 workers with VVERBOSE=1
2.  In a console, enqueue 2 long-running lonely jobs (add a sleep 5 as an example)
3.  Watch 1 worker pick up the first job and start working
4.  Watch 2nd worker repeated pop and push job 2 back onto the queue without any pausing.  This causes 100% of 1 core to be used continually pushing/popping a job until the first job is finished.  Can verify with top.

This can have a negative performance impact on the system.  The normal polling loop for resque workers is [5 seconds](https://github.com/resque/resque/blob/v1.24.1/lib/resque/worker.rb#L129) and can be observed with VVERBOSE.  A suggested fix would be to sleep for [5 seconds](https://github.com/resque/resque/blob/v1.24.1/lib/resque/worker.rb#L166-L168) before each re-enqueue so that the worker is not slamming one of the cores on the server.

**Comment by lwoodson** [comment]
Went ahead and fixed this issue in [this pull request](https://github.com/wallace/resque-lonely_job/pull/9).  I opted to default to a 1 second sleep which should be enough to relax the strain on a CPU.

**Comment by wallace** [comment]
Fixed in #9
